In [22]:
#https://roboreport.co.kr/딥러닝lstm으로-아파트-지수-예측하기-2-lstm-실험하기/
#https://tbacking.com/2017/08/18/순환-신경망-lstm-활용-주가-예측/ 
import os
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import math
from sklearn.metrics import mean_squared_error
import FinanceDataReader as fdr
look_back = 1
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i + look_back)]
        dataX.append(a)
        dataY.append(dataset[i + look_back])
    return np.array(dataX), np.array(dataY)
 
# file loader
sydtpath = "D:sydt"
naturalEndoTekCode = "A168330"
fullpath = sydtpath + os.path.sep + naturalEndoTekCode + '.csv'
pandf = fdr.DataReader("KS11","2018")

# convert nparray
nparr = pandf['Close'].values[::-1]
nparr.astype('float32')
nparr=nparr.reshape(-1,1)
print(nparr)


scaler = MinMaxScaler(feature_range=(0, 1))
nptf = scaler.fit_transform(nparr)
 
# split train, test
train_size = int(len(nptf) * 0.7)
test_size = len(nptf) - train_size
train, test = nptf[0:train_size], nptf[train_size:len(nptf)]
print(len(train), len(test))
 
# create dataset for learning
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)
 
# reshape input to be [samples, time steps, features]
trainX = np.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0], 1, testX.shape[1]))
 
# simple lstm network learning
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=10, batch_size=1, verbose=2)

print("\n 테스트 정확도 : %.4f" % (model.evaluate(testX,testY)))

[[2190.08]
 [2203.71]
 [2204.18]
 [2196.56]
 [2194.76]
 [2195.68]
 [2168.15]
 [2170.25]
 [2137.35]
 [2105.62]
 [2098.  ]
 [2088.65]
 [2081.85]
 [2060.74]
 [2068.89]
 [2084.07]
 [2091.92]
 [2087.96]
 [2118.6 ]
 [2127.85]
 [2121.35]
 [2123.5 ]
 [2101.96]
 [2096.6 ]
 [2125.32]
 [2153.24]
 [2160.69]
 [2162.18]
 [2139.23]
 [2122.45]
 [2140.92]
 [2124.09]
 [2137.23]
 [2144.29]
 [2144.15]
 [2142.64]
 [2130.24]
 [2100.2 ]
 [2083.48]
 [2080.27]
 [2092.69]
 [2093.6 ]
 [2087.89]
 [2085.66]
 [2080.62]
 [2088.86]
 [2064.84]
 [2060.69]
 [2077.94]
 [2082.83]
 [2068.17]
 [2067.4 ]
 [2044.61]
 [2028.15]
 [2046.25]
 [2021.73]
 [2020.69]
 [2031.91]
 [2072.42]
 [2063.05]
 [2049.93]
 [2074.52]
 [2073.39]
 [2101.04]
 [2091.7 ]
 [2091.52]
 [2080.35]
 [2070.73]
 [2062.33]
 [2062.22]
 [2049.2 ]
 [2032.08]
 [2019.55]
 [2009.13]
 [2004.75]
 [1988.53]
 [1965.69]
 [1969.19]
 [1967.79]
 [1933.41]
 [1941.09]
 [1924.6 ]
 [1916.31]
 [1948.3 ]
 [1951.01]
 [1964.65]
 [1960.25]
 [1939.9 ]
 [1927.17]
 [1938.37]
 [1925.83]

In [23]:
nptf

array([[0.40723042],
       [0.42702766],
       [0.42771032],
       [0.41664246],
       [0.414028  ],
       [0.41536428],
       [0.37537764],
       [0.37842784],
       [0.33064141],
       [0.28455438],
       [0.27348652],
       [0.25990588],
       [0.25002905],
       [0.2193673 ],
       [0.23120497],
       [0.25325354],
       [0.26465547],
       [0.25890367],
       [0.30340751],
       [0.3168429 ],
       [0.30740181],
       [0.31052463],
       [0.27923832],
       [0.27145306],
       [0.31316814],
       [0.35372124],
       [0.36454218],
       [0.36670637],
       [0.33337207],
       [0.30899954],
       [0.33582675],
       [0.31138159],
       [0.33046712],
       [0.34072159],
       [0.34051824],
       [0.33832501],
       [0.32031432],
       [0.27668197],
       [0.25239658],
       [0.24773414],
       [0.26577388],
       [0.26709563],
       [0.258802  ],
       [0.25556298],
       [0.24824251],
       [0.2602109 ],
       [0.22532245],
       [0.219

In [15]:
#https://roboreport.co.kr/딥러닝lstm으로-아파트-지수-예측하기-2-lstm-실험하기/

import os
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import math
from sklearn.metrics import mean_squared_error
import FinanceDataReader as fdr
look_back = 1
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i + look_back)]
        dataX.append(a)
        dataY.append(dataset[i + look_back])
    return np.array(dataX), np.array(dataY)
 
# file loader
sydtpath = "D:sydt"
naturalEndoTekCode = "A168330"
fullpath = sydtpath + os.path.sep + naturalEndoTekCode + '.csv'
pandf = fdr.DataReader("KS11","2018")
# convert nparray
nparr = pandf['Close'].values[::-1]
nparr.astype('float32')
nptf = nparr
 
# split train, test
train_size = int(len(nptf) * 0.7)
test_size = len(nptf) - train_size
train, test = nptf[0:train_size], nptf[train_size:len(nptf)]
print(len(train), len(test))
 
# create dataset for learning
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

[2190.08 2203.71 2204.18 2196.56 2194.76 2195.68 2168.15 2170.25 2137.35
 2105.62 2098.   2088.65 2081.85 2060.74 2068.89 2084.07 2091.92 2087.96
 2118.6  2127.85 2121.35 2123.5  2101.96 2096.6  2125.32 2153.24 2160.69
 2162.18 2139.23 2122.45 2140.92 2124.09 2137.23 2144.29 2144.15 2142.64
 2130.24 2100.2  2083.48 2080.27 2092.69 2093.6  2087.89 2085.66 2080.62
 2088.86 2064.84 2060.69 2077.94 2082.83 2068.17 2067.4  2044.61 2028.15
 2046.25 2021.73 2020.69 2031.91 2072.42 2063.05 2049.93 2074.52 2073.39
 2101.04 2091.7  2091.52 2080.35 2070.73 2062.33 2062.22 2049.2  2032.08
 2019.55 2009.13 2004.75 1988.53 1965.69 1969.19 1967.79 1933.41 1941.09
 1924.6  1916.31 1948.3  1951.01 1964.65 1960.25 1939.9  1927.17 1938.37
 1925.83 1942.29 1937.75 1920.61 1909.71 1917.5  1946.98 1998.13 2017.34
 2024.55 2038.68 2029.48 2066.26 2074.48 2082.3  2101.45 2093.34 2094.36
 2066.55 2072.92 2091.87 2082.48 2086.66 2080.58 2058.78 2052.03 2064.17
 2110.59 2108.73 2096.02 2122.02 2129.74 2130.62 21

In [18]:
test

array([2286.5 , 2287.68, 2270.2 , 2307.07, 2295.26, 2293.51, 2294.99,
       2289.06, 2273.03, 2280.2 , 2269.31, 2289.19, 2282.29, 2290.11,
       2297.92, 2301.99, 2310.9 , 2285.06, 2280.62, 2294.16, 2285.8 ,
       2272.87, 2257.55, 2265.46, 2272.76, 2271.54, 2326.13, 2314.24,
       2342.03, 2350.92, 2357.88, 2357.22, 2337.83, 2363.91, 2340.11,
       2376.24, 2404.04, 2423.48, 2468.83, 2470.15, 2451.58, 2470.58,
       2453.76, 2447.76, 2438.96, 2423.01, 2409.03, 2457.25, 2478.96,
       2460.8 , 2466.01, 2471.91, 2465.57, 2460.65, 2448.45, 2459.82,
       2458.54, 2476.11, 2477.71, 2464.16, 2443.98, 2449.81, 2461.38,
       2487.25, 2505.61, 2515.38, 2492.4 , 2475.64, 2448.81, 2464.14,
       2474.11, 2476.33, 2486.1 , 2479.98, 2453.77, 2457.49, 2455.07,
       2442.71, 2444.22, 2450.74, 2444.08, 2429.58, 2437.52, 2408.06,
       2442.43, 2444.16, 2445.85, 2436.37, 2419.29, 2452.06, 2437.08,
       2416.76, 2496.02, 2484.97, 2485.52, 2475.03, 2493.97, 2492.38,
       2486.08, 2494