In [8]:
#숫자 분류 코드
#출처 :https://bcho.tistory.com/1154

#데이타 로딩
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
mnist = input_data.read_data_sets('/tmp/tensorflow/mnist/input_data', one_hot=True)



#모델 생성
x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
k = tf.matmul(x, W) + b
y = tf.nn.softmax(k)



#코스트함수와 옵티마이저 정의
y_ = tf.placeholder(tf.float32, [None, 10])                                                                               
learning_rate = 0.5
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = k,labels = y_))
train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


#세션 초기화
print ("Training")
sess = tf.Session()
init = tf.global_variables_initializer() #.run()
sess.run(init)

# 트레이닝 시작
for _ in range(1000):
    # 1000번씩, 전체 데이타에서 100개씩 뽑아서 트레이닝을 함.  
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
print ('b is ',sess.run(b))
print('W is',sess.run(W))

#검증 코드
print ("Testing model")
# Test trained model
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('accuracy ',sess.run(accuracy, feed_dict={x: mnist.test.images,y_: mnist.test.labels}))
print ("done")




Extracting /tmp/tensorflow/mnist/input_data\train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-labels-idx1-ubyte.gz
Training
b is  [-0.3815548   0.36858532  0.08419519 -0.25622338  0.0235133   1.289862
 -0.08539795  0.64561456 -1.4326872  -0.25590906]
W is [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Testing model
accuracy  0.9172
done
